### ISSUE TITLE
无法添加依赖

### ISSUE THREAD

**Issue by jxtx123456** [HuolalaTech/batteryfinder-android#3]
![image](https://github.com/HuolalaTech/batteryfinder-android/assets/10148767/f5aab65b-d6b4-49cd-b191-e10357abf54b)
使用的Androidstudio版本
![image](https://github.com/HuolalaTech/batteryfinder-android/assets/10148767/2c50fa25-8e4f-4058-a02c-376a6c1d2a4f)
即使使用demo代码也是一样

**Comment by TestPlanB** [comment]
如果遇到插件无法下载的问题，可以先执行gradle 上传插件到本地：再进行项目编译
![image](https://github.com/HuolalaTech/batteryfinder-android/assets/65278264/70c85472-7f31-49d9-9f21-ad6a4d35ef8c)

**Comment by jxtx123456** [comment]
你这个编译都无法通过，无法运行这个task，就不能直接放在Maven库里吗？

**Comment by zienn** [comment]
一样的问题，怎么先上传到本地？

**Comment by jxtx123456** [comment]
> 如果遇到插件无法下载的问题，可以先执行gradle 上传插件到本地：再进行项目编译 ![image](https://private-user-images.githubusercontent.com/65278264/346809247-70c85472-7f31-49d9-9f21-ad6a4d35ef8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTA0ODUsIm5iZiI6MTcyMzQ1MDE4NSwicGF0aCI6Ii82NTI3ODI2NC8zNDY4MDkyNDctNzBjODU0NzItN2YzMS00OWQ5LTlmMjEtYWQ2YTRkMzVlZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA4MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NmY5MGExMDE3ZDBhMjJhZTljZDc4Mjg1NDQ1MjU0ZjczZTYwOWQxMDViZmU4OTc0MjY2YTJhZWVlYjU1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xg7V6bW6qiSo1PKeSoGqFvCdsBu3H3wyBtkaIy7EtPw)

你这个编译都无法通过，无法运行这个task，就不能直接放在Maven库里吗？

**Comment by zienn** [comment]
> > 如果遇到插件无法下载的问题，可以先执行gradle 上传插件到本地：再进行项目编译 ![image](https://private-user-images.githubusercontent.com/65278264/346809247-70c85472-7f31-49d9-9f21-ad6a4d35ef8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTA0ODUsIm5iZiI6MTcyMzQ1MDE4NSwicGF0aCI6Ii82NTI3ODI2NC8zNDY4MDkyNDctNzBjODU0NzItN2YzMS00OWQ5LTlmMjEtYWQ2YTRkMzVlZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA4MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NmY5MGExMDE3ZDBhMjJhZTljZDc4Mjg1NDQ1MjU0ZjczZTYwOWQxMDViZmU4OTc0MjY2YTJhZWVlYjU1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xg7V6bW6qiSo1PKeSoGqFvCdsBu3H3wyBtkaIy7EtPw)
> 
> 你这个编译都无法通过，无法运行这个task，就不能直接放在Maven库里吗？

可以先把依赖它的先注释掉，然后运行这个task
